server:
  port: 808
dubbo:
  protocol:
    port: -1
  application:
    name: user-cur
  consumer:
    check: false
  registry:
    address: zookeeper://106.54.121.68:2181
    timeout: 10000
spring:
  thymeleaf:
    cache: false
